### ISSUE TITLE
Joining paths?

### ISSUE THREAD

**Issue by rauschma** [jaredly/reason-cli-tools#1]
The API is nicely complete. One thing that seems to be missing is a cross-platform way of joining paths (e.g. when recursing into a tree of directories).

**Comment by tesla3327** [comment]
This function is built-in:
https://github.com/jaredly/pack.re/blob/93e1fabc8547e793cae61704667896ee5e244513/src/fixFile.re#L36

**Comment by rauschma** [comment]
Nice, wasn’t aware!
